# Generated by Django 6.1 on 2026-08-13 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="energy",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="user",
            name="energy_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_day",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="login_streak",
            field=models.IntegerField(default=0),
        ),
    ]
