# Generated by Django 6.0.2 on 2026-08-13 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0004_user_is_banned"),
    ]

    operations = [
        migrations.AddField(
            model_name="alliance",
            name="last_heisted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alliance",
            name="treasury_gold",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="duellog",
            name="wager_gold",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.CharField(max_length=16)),
                ("template_key", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=64)),
                ("rarity", models.CharField(default="common", max_length=16)),
                ("level", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipped_on",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_items",
                        to="bio_lab.creature",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="bio_lab.user",
                    ),
                ),
            ],
        ),
    ]
