# Generated by Django 6.0.2 on 2026-08-13 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0005_alliance_last_heisted_at_alliance_treasury_gold_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequiredChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.BigIntegerField(unique=True)),
                ("username", models.CharField(blank=True, max_length=64, null=True)),
                ("title", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "invite_link",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("reward_coins", models.IntegerField(default=0)),
                ("reward_dna", models.IntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChannelJoinClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bio_lab.user"
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bio_lab.requiredchannel",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "channel"), name="uq_channel_join_claim"
                    )
                ],
            },
        ),
    ]
