# Generated by Django 6.0.2 on 2026-08-13 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0006_requiredchannel_channeljoinclaim"),
    ]

    operations = [
        migrations.AddField(
            model_name="creature",
            name="star_level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="diamonds",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building_type", models.CharField(max_length=32)),
                ("level", models.IntegerField(default=1)),
                (
                    "last_collected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings",
                        to="bio_lab.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuildingUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_level", models.IntegerField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finishes_at", models.DateTimeField()),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="bio_lab.building",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="building_upgrade",
                        to="bio_lab.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpeedupCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minutes", models.IntegerField()),
                ("count", models.IntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speedup_cards",
                        to="bio_lab.user",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="building",
            constraint=models.UniqueConstraint(
                fields=("owner", "building_type"), name="uq_owner_building_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="speedupcard",
            constraint=models.UniqueConstraint(
                fields=("owner", "minutes"), name="uq_owner_speedup_minutes"
            ),
        ),
    ]
