# Generated by Django 6.0.2 on 2026-08-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0007_creature_star_level_user_diamonds_building_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lab_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
