# Generated by Django 6.0.2 on 2026-08-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0008_user_lab_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="requiredchannel",
            name="reward_diamonds",
            field=models.IntegerField(default=0),
        ),
    ]
