# Generated by Django 6.0.2 on 2026-08-13 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0009_requiredchannel_reward_diamonds"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cup",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="shield_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AttackLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("defender_label", models.CharField(max_length=64)),
                ("is_fake_defender", models.BooleanField(default=False)),
                ("attacker_won", models.BooleanField()),
                ("loot_gold", models.IntegerField(default=0)),
                ("cup_delta", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attacker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacks_made",
                        to="bio_lab.user",
                    ),
                ),
                (
                    "defender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacks_received",
                        to="bio_lab.user",
                    ),
                ),
            ],
        ),
    ]
