# Generated by Django 6.0.2 on 2026-08-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0010_user_cup_user_shield_until_attacklog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="level",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="coins",
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name="user",
            name="diamonds",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="dna_fragments",
            field=models.IntegerField(default=100),
        ),
    ]
