# Generated by Django 6.0.2 on 2026-08-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0013_backfill_welcome_package"),
    ]

    operations = [
        migrations.CreateModel(
            name="ButtonEmojiOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=48, unique=True)),
                ("custom_emoji_id", models.CharField(max_length=64)),
                ("placeholder", models.CharField(max_length=16)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
