# Generated by Django 6.0.2 on 2026-08-14 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0014_buttonemojioverride"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_closed_week",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SeasonResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_key", models.CharField(max_length=10)),
                ("rank", models.IntegerField()),
                ("cup_before", models.IntegerField()),
                ("cup_after", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_results",
                        to="bio_lab.user",
                    ),
                ),
            ],
            options={
                "ordering": ("-week_key", "rank"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("week_key", "user"), name="uq_season_result"
                    )
                ],
            },
        ),
    ]
