# Generated by Django 6.1 on 2026-08-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0015_seasonstate_seasonresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="ButtonStyleOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=32, unique=True)),
                ("style", models.CharField(blank=True, max_length=16)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ThemeLoadout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=48, unique=True)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("payload", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-is_active", "name"),
            },
        ),
    ]
