# Generated by Django 6.1 on 2026-08-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0016_buttonstyleoverride_themeloadout"),
    ]

    operations = [
        migrations.CreateModel(
            name="ButtonKeyStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=48, unique=True)),
                ("style", models.CharField(blank=True, max_length=16)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
