# Generated by Django 6.1 on 2026-08-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0017_buttonkeystyle"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lab_xp",
            field=models.IntegerField(default=0),
        ),
    ]
