# Generated by Django 6.1 on 2026-08-14 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0019_breedingjob_creatureassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordRewardClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_claimed_at", models.DateTimeField()),
                ("total_claims", models.IntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_rewards",
                        to="bio_lab.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_rewards",
                        to="bio_lab.user",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "group"), name="uq_word_reward_claim"
                    )
                ],
            },
        ),
    ]
