# Generated by Django 5.2.17 on 2026-08-17 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0020_wordrewardclaim"),
    ]

    operations = [
        migrations.CreateModel(
            name="Egg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_rarity", models.CharField(default="common", max_length=16)),
                ("upgrade_chance", models.FloatField(default=0.0)),
                ("parent_a_name", models.CharField(max_length=64)),
                ("parent_a_element", models.CharField(max_length=16)),
                ("parent_b_name", models.CharField(max_length=64)),
                ("parent_b_element", models.CharField(max_length=16)),
                ("inherit_level", models.IntegerField(default=1)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finishes_at", models.DateTimeField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eggs",
                        to="bio_lab.user",
                    ),
                ),
            ],
            options={
                "ordering": ("finishes_at",),
            },
        ),
    ]
