# Generated by Django 5.2.17 on 2026-08-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0022_achievementclaim"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lab_renames",
            field=models.IntegerField(default=0),
        ),
    ]
