# Generated by Django 5.2.17 on 2026-08-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0023_user_lab_renames"),
    ]

    operations = [
        migrations.AddField(
            model_name="attacklog",
            name="defender_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="breedingjob",
            name="notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="buildingupgrade",
            name="notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="egg",
            name="notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="energy_full_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_nudge_day",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notifications_on",
            field=models.BooleanField(default=True),
        ),
    ]
