# Generated by Django 5.2.17 on 2026-08-18 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0024_attacklog_defender_notified_breedingjob_notified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_key", models.CharField(max_length=10)),
                ("points", models.IntegerField(default=0)),
                ("premium", models.BooleanField(default=False)),
                ("free_claimed", models.IntegerField(default=0)),
                ("premium_claimed", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pass_progress",
                        to="bio_lab.user",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "season_key"), name="uq_pass_progress"
                    )
                ],
            },
        ),
    ]
