# Generated by Django 5.2.17 on 2026-08-18 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0025_passprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_bonus_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="referred_by",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CodexEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("species", models.CharField(max_length=64)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codex_entries",
                        to="bio_lab.user",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "species"), name="uq_codex_entry"
                    )
                ],
            },
        ),
    ]
