# Generated by Django 5.2.17 on 2026-08-18 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0026_user_referral_bonus_paid_user_referred_by_codexentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="campaign_stage",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team",
                        to="bio_lab.user",
                    ),
                ),
                (
                    "slot1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bio_lab.creature",
                    ),
                ),
                (
                    "slot2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bio_lab.creature",
                    ),
                ),
                (
                    "slot3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bio_lab.creature",
                    ),
                ),
            ],
        ),
    ]
