# Generated by Django 5.2.17 on 2026-08-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0027_user_campaign_stage_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_event_claim_day",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
