# Generated by Django 5.2.17 on 2026-08-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0028_user_last_event_claim_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="banner_pity",
            field=models.IntegerField(default=0),
        ),
    ]
