# Generated by Django 5.2.17 on 2026-08-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0029_user_banner_pity"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllianceWarState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_settled_week",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="alliance",
            name="pass_perk_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="alliance",
            name="war_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="alliance",
            name="war_week",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="alliance",
            name="xp_perk_level",
            field=models.IntegerField(default=0),
        ),
    ]
