# Generated by Django 5.2.17 on 2026-08-18 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0030_alliancewarstate_alliance_pass_perk_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="idle_since",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="user",
            name="last_dungeon_day",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
