# Generated by Django 5.2.17 on 2026-08-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0031_user_idle_since_user_last_dungeon_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_shop_day",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="title",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
