# Generated by Django 5.2.17 on 2026-08-20 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0032_user_last_shop_day_user_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=24)),
                ("message_id", models.IntegerField(blank=True, null=True)),
                ("reward_json", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField()),
                ("expired_notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bio_lab.user",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drops",
                        to="bio_lab.group",
                    ),
                ),
            ],
        ),
    ]
