# Generated by Django 5.2.17 on 2026-08-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0033_groupdrop"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupdrop",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
