# Generated by Django 6.1 on 2026-08-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0035_attacklog_attacker_fields_revenge_energy50"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_game_url",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "group_game_title",
                    models.CharField(blank=True, default="", max_length=48),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
