# Generated by Django 6.1 on 2026-08-24 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0036_botconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="alliance",
            name="barracks_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="alliance",
            name="fortress_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="alliance",
            name="vault_collected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alliance",
            name="vault_level",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="AllianceWar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_a", models.IntegerField(default=0)),
                ("score_b", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ends_at", models.DateTimeField()),
                ("status", models.CharField(default="active", max_length=12)),
                (
                    "alliance_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wars_as_a",
                        to="bio_lab.alliance",
                    ),
                ),
                (
                    "alliance_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wars_as_b",
                        to="bio_lab.alliance",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bio_lab.alliance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AllianceWarHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("power", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="bio_lab.user",
                    ),
                ),
                (
                    "war",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hits",
                        to="bio_lab.alliancewar",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("war", "user"), name="uq_alliance_war_hit"
                    )
                ],
            },
        ),
    ]
