# Generated by Django 6.1 on 2026-08-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0037_alliance_barracks_level_alliance_fortress_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="raid_level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="raidboss",
            name="level",
            field=models.IntegerField(default=1),
        ),
    ]
