# Generated by Django 6.1 on 2026-08-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0038_group_raid_level_raidboss_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="group_shield_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
