# Generated by Django 6.1 on 2026-08-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0039_user_group_shield_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="botconfig",
            name="backup_interval_hours",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="botconfig",
            name="backup_last_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
