# Generated by Django 5.2.17 on 2026-08-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0040_botconfig_backup_interval_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="botconfig",
            name="backup_chat_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
