# Generated by Django 5.2.17 on 2026-08-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0041_botconfig_backup_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="alliance",
            name="hall_level",
            field=models.IntegerField(default=0),
        ),
    ]
