# Generated by Django 5.2.17 on 2026-08-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0042_alliance_hall_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="drop_claim_ready_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reward_ready_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reward_total_claims",
            field=models.IntegerField(default=0),
        ),
    ]
