# Generated by Django 5.2.17 on 2026-08-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0043_user_drop_claim_ready_at_user_reward_ready_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("emoji", models.CharField(default="🎁", max_length=8)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("price_coins", models.IntegerField(default=0)),
                ("price_diamonds", models.IntegerField(default=0)),
                ("contents_json", models.TextField(default="[]")),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
