# Generated by Django 5.2.17 on 2026-08-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0044_shopitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="equip_transfer_ready_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="kaiju_transfer_ready_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
