# Generated by Django 5.2.17 on 2026-08-25 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0045_user_equip_transfer_ready_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alliance",
            name="deputy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="bio_lab.user",
            ),
        ),
    ]
