# Generated by Django 5.2.17 on 2026-08-26 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0046_alliance_deputy"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopitem",
            name="max_per_user",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ShopItemPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="bio_lab.shopitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bio_lab.user"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "item"), name="uq_shop_purchase"
                    )
                ],
            },
        ),
    ]
