# Generated by Django 6.1 on 2026-08-27 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0047_shopitem_max_per_user_shopitempurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="alliance",
            name="auto_accept",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="alliance",
            name="min_join_power",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="AllianceJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alliance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="bio_lab.alliance",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="bio_lab.user",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "alliance"), name="uq_alliance_join_request"
                    )
                ],
            },
        ),
    ]
