# Generated by Django 5.2.17 on 2026-08-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0048_alliance_auto_accept_alliance_min_join_power_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="vein_claim_ready_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
