# Generated by Django 5.2.17 on 2026-08-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0049_user_vein_claim_ready_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="banked_pending",
            field=models.FloatField(default=0.0),
        ),
    ]
