# Generated by Django 5.2.17 on 2026-09-08 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0068_group_special_drop_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=32)),
                ("level", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ResearchUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=32)),
                ("target_level", models.IntegerField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finishes_at", models.DateTimeField()),
                ("notified", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameIndex(
            model_name="purchaserequest",
            new_name="bio_lab_pur_user_id_610a5e_idx",
            old_name="bio_lab_pur_user_id_status_idx",
        ),
        migrations.AddField(
            model_name="research",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="research",
                to="bio_lab.user",
            ),
        ),
        migrations.AddField(
            model_name="researchupgrade",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="research_upgrades",
                to="bio_lab.user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="research",
            unique_together={("owner", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="researchupgrade",
            unique_together={("owner", "key")},
        ),
    ]
