# Generated by Django 5.2.17 on 2026-09-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0069_research_researchupgrade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requiredchannel",
            name="kind",
            field=models.CharField(default="channel", max_length=16),
        ),
    ]
