# Generated by Django 5.2.17 on 2026-09-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0070_requiredchannel_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="biocrate_tickets",
            field=models.IntegerField(default=0),
        ),
    ]
