# Generated by Django 5.2.17 on 2026-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0071_user_biocrate_tickets"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gem_kaiju_claimed_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
