# Generated by Django 5.2.17 on 2026-09-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0072_user_gem_kaiju_claimed_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="xp_capsules",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
