# Generated by Django 5.2.17 on 2026-09-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0073_user_xp_capsules"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="transfer_notify",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="transfers_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
