# Generated by Django 5.2.17 on 2026-09-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0074_user_transfer_notify_user_transfers_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lab_level_notified",
            field=models.IntegerField(default=0),
        ),
    ]
