# Generated by Django 5.2.17 on 2026-09-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0075_user_lab_level_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="started_gate",
            field=models.BooleanField(default=False),
        ),
    ]
