# Generated by Django 5.2.17 on 2026-09-14 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0076_user_started_gate"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="subscription_tier",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="user",
            name="last_free_box_nudge_day",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_tier",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ArenaChest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.IntegerField()),
                ("chest_type", models.CharField(max_length=32)),
                ("cup_at_drop", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("locked", "locked"),
                            ("unlocking", "unlocking"),
                            ("queued", "queued"),
                            ("ready", "ready"),
                        ],
                        default="locked",
                        max_length=16,
                    ),
                ),
                ("unlock_starts_at", models.DateTimeField(blank=True, null=True)),
                ("unlock_finishes_at", models.DateTimeField(blank=True, null=True)),
                ("notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arena_chests",
                        to="bio_lab.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="bio_lab_are_user_id_e6804c_idx"
                    ),
                    models.Index(
                        fields=["status", "unlock_finishes_at"],
                        name="bio_lab_are_status_481c41_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "slot"), name="uq_user_arena_chest_slot"
                    )
                ],
            },
        ),
    ]
