# Generated by Django 5.2.17 on 2026-09-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0077_purchaserequest_subscription_tier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchasePack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("emoji", models.CharField(blank=True, default="🎁", max_length=8)),
                ("coins", models.BigIntegerField(default=0)),
                ("dna", models.BigIntegerField(default=0)),
                ("diamonds", models.BigIntegerField(default=0)),
                ("price_toman", models.BigIntegerField(default=0)),
                ("discount_percent", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
