# Generated by Django 5.2.17 on 2026-09-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0079_normalize_creature_base_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="creature",
            name="fusion_ready_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
