# Generated by Django 5.2.17 on 2026-09-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0080_creature_fusion_ready_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creature",
            name="fusion_ready_at",
        ),
    ]
