# Generated by Django 5.2.17 on 2026-09-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0081_remove_creature_fusion_ready_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attacklog",
            name="attacker_label",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="attacklog",
            name="defender_label",
            field=models.CharField(max_length=255),
        ),
    ]
