# Generated by Django 5.2.17 on 2026-09-18 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0082_alter_attacklog_attacker_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_expedition_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mugen_tower_floor",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="plundered_alert_dna",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="plundered_alert_gold",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="BlackMarketAuction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("item_type", models.CharField(max_length=32)),
                ("item_payload", models.JSONField(blank=True, default=dict)),
                ("bid_currency", models.CharField(default="coins", max_length=16)),
                ("min_bid", models.IntegerField(default=1000)),
                ("current_bid", models.IntegerField(default=0)),
                (
                    "highest_bidder_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("ends_at", models.DateTimeField()),
                ("is_settled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "highest_bidder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_auctions",
                        to="bio_lab.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="GroupExpedition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.BigIntegerField(db_index=True)),
                (
                    "group_title",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recruiting", "در حال عضوگیری"),
                            ("in_progress", "در حال اکتشاف"),
                            ("completed", "تکمیل شده"),
                            ("failed", "شکست خورده"),
                            ("expired", "منقضی شده"),
                        ],
                        default="recruiting",
                        max_length=16,
                    ),
                ),
                (
                    "target_name",
                    models.CharField(
                        default="دره استخوان\u200cهای اژدها", max_length=128
                    ),
                ),
                ("difficulty", models.CharField(default="normal", max_length=16)),
                ("total_gold", models.IntegerField(default=0)),
                ("total_dna", models.IntegerField(default=0)),
                ("total_diamonds", models.IntegerField(default=0)),
                ("log_text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_expeditions",
                        to="bio_lab.user",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="expeditions", to="bio_lab.user"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
