# Generated by Django 5.2.17 on 2026-09-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0083_user_last_expedition_at_user_mugen_tower_floor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attacklog",
            name="loot_dna",
            field=models.IntegerField(default=0),
        ),
    ]
