# Generated by Django 5.2.17 on 2026-09-19 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0084_attacklog_loot_dna"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breedingjob",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breeding_jobs",
                to="bio_lab.user",
            ),
        ),
    ]
