# Generated by Django 5.2.17 on 2026-09-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0085_alter_breedingjob_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="blackmarketauction",
            name="winner_notified",
            field=models.BooleanField(default=False),
        ),
    ]
