# Generated by Django 5.2.17 on 2026-09-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0086_blackmarketauction_winner_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="alliancewar",
            name="notified_30m",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alliancewar",
            name="notified_6h",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alliancewar",
            name="notified_start",
            field=models.BooleanField(default=False),
        ),
    ]
