# Generated by Django 5.2.17 on 2026-09-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0087_alliancewar_notified_30m_alliancewar_notified_6h_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="story_step",
            field=models.IntegerField(default=0),
        ),
    ]
