# Generated by Django 5.2.17 on 2026-10-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0088_user_onboarding_completed_user_story_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blackmarketauction",
            name="highest_bidder_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
