# Generated by Django 5.2.17 on 2026-10-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0089_alter_blackmarketauction_highest_bidder_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attacklog",
            index=models.Index(
                fields=["defender", "-created_at"], name="attacklog_def_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attacklog",
            index=models.Index(
                fields=["attacker", "attacker_won"], name="attacklog_atk_won_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creature",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["owner", "id"],
                name="creature_active_owner_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["cup", "id"], name="user_cup_id_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["mugen_tower_floor"], name="user_mugen_floor_idx"
            ),
        ),
    ]
