# Generated by Django 5.2.17 on 2026-10-05 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0090_attacklog_attacklog_def_recent_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_day", models.CharField(max_length=10)),
                ("offer_idx", models.PositiveSmallIntegerField()),
                ("template_key", models.CharField(max_length=32)),
                ("hours", models.PositiveSmallIntegerField()),
                ("reward", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finishes_at", models.DateTimeField()),
                ("status", models.CharField(default="active", max_length=12)),
                ("notified", models.BooleanField(default=False)),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="bio_lab.creature",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_missions",
                        to="bio_lab.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner", "status"], name="dispatch_owner_status_idx"
                    ),
                    models.Index(
                        fields=["status", "notified", "finishes_at"],
                        name="dispatch_due_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "offer_day", "offer_idx"),
                        name="uq_dispatch_offer_once",
                    )
                ],
            },
        ),
    ]
