# Generated by Django 5.2.17 on 2026-10-05 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0091_dispatch_missions"),
    ]

    operations = [
        migrations.CreateModel(
            name="FestivalState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_settled_key",
                    models.CharField(blank=True, default="", max_length=16),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorldBossState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("next_spawn_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorldBoss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("element", models.CharField(max_length=16)),
                ("max_hp", models.BigIntegerField()),
                ("current_hp", models.BigIntegerField()),
                ("spawned_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("status", models.CharField(default="active", max_length=12)),
                ("settled", models.BooleanField(default=False)),
                (
                    "killer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bio_lab.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorldBossHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hits", models.PositiveSmallIntegerField(default=0)),
                ("damage", models.BigIntegerField(default=0)),
                (
                    "boss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hits",
                        to="bio_lab.worldboss",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="bio_lab.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FestivalProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("festival_key", models.CharField(max_length=16)),
                ("coins", models.IntegerField(default=0)),
                ("earned", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="bio_lab.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["festival_key", "-earned"], name="festival_rank_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "festival_key"), name="uq_festival_progress"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FestivalPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("festival_key", models.CharField(max_length=16)),
                ("item_key", models.CharField(max_length=32)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="bio_lab.user",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "festival_key", "item_key"),
                        name="uq_festival_purchase",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="worldboss",
            index=models.Index(
                fields=["status", "settled"], name="worldboss_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="worldbosshit",
            index=models.Index(
                fields=["boss", "-damage"], name="worldboss_hit_rank_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="worldbosshit",
            constraint=models.UniqueConstraint(
                fields=("boss", "user"), name="uq_worldboss_hit"
            ),
        ),
    ]
