# Generated by Django 5.2.17 on 2026-10-05 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0092_worldboss_festival"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_key", models.CharField(max_length=10, unique=True)),
                ("status", models.CharField(default="registration", max_length=14)),
                ("round", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TournamentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_no", models.PositiveSmallIntegerField(default=0)),
                ("alive", models.BooleanField(default=True)),
                ("place", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bio_lab.creature",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="bio_lab.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="bio_lab.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_no", models.PositiveSmallIntegerField()),
                ("round", models.PositiveSmallIntegerField()),
                ("slot", models.PositiveSmallIntegerField()),
                ("power_a", models.IntegerField(default=0)),
                ("power_b", models.IntegerField(default=0)),
                ("element_a", models.CharField(blank=True, default="", max_length=16)),
                ("element_b", models.CharField(blank=True, default="", max_length=16)),
                (
                    "a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="bio_lab.tournamententry",
                    ),
                ),
                (
                    "b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="bio_lab.tournamententry",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="bio_lab.tournament",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="bio_lab.tournamententry",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tournamententry",
            index=models.Index(
                fields=["tournament", "group_no"], name="tournament_group_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamententry",
            constraint=models.UniqueConstraint(
                fields=("tournament", "user"), name="uq_tournament_entry"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentmatch",
            constraint=models.UniqueConstraint(
                fields=("tournament", "group_no", "round", "slot"),
                name="uq_tournament_match",
            ),
        ),
    ]
