# Generated by Django 5.2.17 on 2026-10-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0094_announcement_marks"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_off",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="ActivityHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                ("day", models.CharField(max_length=10)),
                ("hour", models.PositiveSmallIntegerField()),
                ("private", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["day", "hour"], name="activity_day_hour_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "day", "hour"), name="uq_activity_hour"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ButtonClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=10)),
                ("key", models.CharField(max_length=48)),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "key"), name="uq_button_click"
                    )
                ],
            },
        ),
    ]
