# Generated by Django 5.2.17 on 2026-10-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0095_metrics_notify_prefs"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=10)),
                ("hour", models.PositiveSmallIntegerField()),
                ("action", models.CharField(max_length=32)),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "hour", "action"), name="uq_action_hour"
                    )
                ],
            },
        ),
    ]
