# Generated by Django 5.2.17 on 2026-10-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0096_action_hour"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoGift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("interval_days", models.PositiveIntegerField(default=4)),
                ("coins", models.BigIntegerField(default=0)),
                ("dna", models.BigIntegerField(default=0)),
                ("diamonds", models.IntegerField(default=0)),
                ("last_at", models.DateTimeField(blank=True, null=True)),
                ("runs", models.IntegerField(default=0)),
            ],
        ),
    ]
