# Generated by Django 5.2.17 on 2026-10-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_lab", "0097_autogift"),
    ]

    operations = [
        migrations.CreateModel(
            name="MiniAppProbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("html_at", models.DateTimeField(blank=True, null=True)),
                ("report_at", models.DateTimeField(blank=True, null=True)),
                ("opens", models.IntegerField(default=0)),
                ("sdk_ok", models.BooleanField(default=False)),
                ("auth_ok", models.BooleanField(default=False)),
                ("img_ok", models.BooleanField(default=False)),
                ("load_ms", models.IntegerField(blank=True, null=True)),
                ("img_ms", models.IntegerField(blank=True, null=True)),
                ("platform", models.CharField(blank=True, default="", max_length=24)),
                ("version", models.CharField(blank=True, default="", max_length=16)),
                ("failed_reported", models.BooleanField(default=False)),
            ],
        ),
    ]
